;   PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
;   Please visit documentation for the other options and examples
;   https://docs.platformio.org/page/projectconf.html

; Идентификатор окружения
[env:esp32-s3-devkitc-1]
;   Крайне важная настройка, так как
;   Она определяет правильную карту выводов (pinout), настройки Flash-памяти и PSRAM (8 МБ для чипа ESP32-S3)
;   Неверная конфигурация приведет к ошибкам загрузки, 
;   Сбоям PSRAM или неработоспособности периферии,
;   В то время как правильная гарантирует стабильную работу,
;   Включая использование двухъядерного процессора LX7

;   Платформа
platform = espressif32 @ 6.9.0
;   Платформа - исходное понятие
;   Она указывает PlatformIO использовать соотвествующие
;   Тулчейн, компилятор и основные библиотеки

;   Конкретная модель платы
board = esp32-s3-devkitc-1
;   Таким образом, PlatformIO подставляет
;   Предопределенные параметры: размеры flash, доступные выводы, тип чипа

;   Фреймворк для платы
framework = espidf
;   Выбран официальный родной фреймворк для esp32
;   По сути определяет инструменты и правила прошивки из кода в процессор

;   Скорость монитора
monitor_speed = 115200
;   Выбрана стандартная скорость для совместимости
;   Параметр принципиален, поскольку прошивка и чтение через Serial осуществляются
;   Через UART-интерфейс с заранее оговоренной скоростью передачи

;   Флаги компиляции и конфигурации
;   Режим работы flash памяти
board_build.flash_mode = qio
;   Определяет режим работы SPI-шины между процессором esp32-s3 и внешней микросхемой flash-памяти
;   В стандартном SPI используется 1 линия данных
;   Quad I/O (4-битный режим, то есть 4 линии данных) - максимальная производительность
;   Octal I/O ещё быстрее, но перестают работать некоторые пины номером больше 20
;   I/O (input/output) означает, что по 4 линиям передаются не только сами данные, но и адреса памяти
board_build.f_cpu = 240000000L
;   Устанавливается статическая максимальная частота для процессора 240 МГц
;   esp32-s3 имеет возможность менять эту частоту динамически

; Включаем PSRAM (очень важно!)
board_build.psram = enable
;   Включает поддержку PSRAM (Pseudostatic RAM) - дополнительной оперативной памяти
;   SRAM (стандартная оперативная память) - 512 Кб
;   PSRAM (дополнительная оперативная память) - 8 Мб

board_build.psram_mode = octal  ; quad или octal, зависит от твоей платы (N16R8 обычно Octal)

;   Опции менюконфига, которые нужно применить принудительно
board_upload.flash_size = 16MB
;   Указывает размер flash-памяти на плате 
;   Важно для правильной адресации и размещения данных

; 1. PSRAM обязателен - без него многие примеры с большими буферами, LVGL, камерами будут падать с ошибками памяти

; 2. Режим PSRAM - неверный режим приведет к ошибкам чтения/записи памяти

; 3. Частота CPU - максимальная производительность для вычислений

; 4. Flash size - если указать меньше, чем есть, верхняя часть памяти будет недоступна

; Дополнительные компоненты, если нужны (Проще получать через git clone)
; lib_deps =

; Настройки загрузки
upload_protocol = esptool
upload_speed = 921600

; Явно указываем метод сброса
board_build.upload.resetmethod = ck

; Альтернативный вариант (попробуй, если ck не сработает)
; board_build.upload.resetmethod = nodemcu

;   Указываем явно, что за микроконтроллер
board_build.mcu = esp32s3

;   Увеличиваем стек для main задачи
board_build.arduino.stack_size = 16384  ; 16 KB

;   Определение структуры разделов во flash-памяти
board_build.partitions = partitions.csv

;   Чтобы изменения заголовков были видны для линкера
lib_ldf_mode = deep+

;   Флаги для аспектов работы нейросети, памяти и поключения библиотек
build_flags = 
    -fno-strict-aliasing
    -fno-tree-vectorize
    -O2
    -fno-tree-vectorize
    -Iinclude
    -Ilib/audio
    -Ilib/led
    -Ilib/sd_card
    -Ilib/watchdog_timer
    -Ilib/wav
    -Ilib/cnn
    -Wno-error=format
    -Wno-format
    -mfix-esp32-psram-cache-issue
    -mfix-esp32-psram-cache-strategy=memw
    -D CONFIG_SPIRAM_IGNORE_NOTFOUND=1
    -D CONFIG_SPIRAM_USE_CAPS_ALLOC=0
    -D CONFIG_ESP32S3_INSTRUCTION_CACHE_16KB=1
    -D CONFIG_ESP32S3_DATA_CACHE_16KB=1
    -D TF_LITE_STATIC_MEMORY

board_build.cmake_extra_args = 
    -DCONFIG_SPIRAM=y
    -DCONFIG_SPIRAM_MODE_OCT=y
    -DCONFIG_SPIRAM_SPEED_40M=y
    -DCONFIG_SPIRAM_ALLOW_BSS_SEG_EXTERNAL_MEMORY=n
    -DCONFIG_SPIRAM_USE_CAPS_ALLOC=n
    -DCONFIG_SPIRAM_FETCH_INSTRUCTIONS=n
    -DCONFIG_SPIRAM_RODATA=n
    -DCONFIG_ESPTOOLPY_FLASHSIZE_16MB=y
    -DCONFIG_PARTITION_TABLE_CUSTOM=y
    -DCONFIG_PARTITION_TABLE_CUSTOM_FILENAME="partitions.csv"